
#include "../fei.h"
#include "../array.c"
#include "../class.c"
#include "../compiler.c"
#include "../corelib.c"
#include "../debug.c"
#include "../main.c"
#include "../mem.c"
#include "../object.c"
#include "../state.c"
#include "../string.c"
#include "../table.c"
#include "../tostring.c"
#include "../value.c"
#include "../vm.c"
#include "../writer.c"
